[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "monitoringpy"
version = "0.1.0"
description = "A Python package for monitoring function calls and generating execution graphs"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "LiveProbes" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "jsonpickle",
    "graphviz",
]

[project.scripts]
monitoringpy-graph = "monitoringpy.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/monitoringpy"] 