[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pymonitor"
version = "0.1.0"
description = "A Python monitoring tool for tracking function execution"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
    { name = "LiveProbes" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "flask>=2.0.0",
    "flask-cors>=4.0.0",
    "sqlalchemy>=2.0.0",
    "pydantic>=2.0.0",
    "mcp>=0.1.0",
]

[project.scripts]
monitoringpy-graph = "monitoringpy.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/monitoringpy"] 